// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMltFS_rqS7rNd3aEiFvRhWvvcocjOhKg',
    appId: '1:32266065148:web:f8c5d94faef0d7397cf379',
    messagingSenderId: '32266065148',
    projectId: 'evently-events',
    authDomain: 'evently-events.firebaseapp.com',
    storageBucket: 'evently-events.firebasestorage.app',
    measurementId: 'G-M0K04G6NKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD44EGYPePrfQdOgQrwbRFfA9vbo18ikTU',
    appId: '1:32266065148:android:78a00bde847624977cf379',
    messagingSenderId: '32266065148',
    projectId: 'evently-events',
    storageBucket: 'evently-events.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm_0IZyZKkstN9YjbYdHDtM4gE8ytH3QI',
    appId: '1:32266065148:ios:95b52242f326677a7cf379',
    messagingSenderId: '32266065148',
    projectId: 'evently-events',
    storageBucket: 'evently-events.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm_0IZyZKkstN9YjbYdHDtM4gE8ytH3QI',
    appId: '1:32266065148:ios:95b52242f326677a7cf379',
    messagingSenderId: '32266065148',
    projectId: 'evently-events',
    storageBucket: 'evently-events.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMltFS_rqS7rNd3aEiFvRhWvvcocjOhKg',
    appId: '1:32266065148:web:8f0f4b44c71a5dbc7cf379',
    messagingSenderId: '32266065148',
    projectId: 'evently-events',
    authDomain: 'evently-events.firebaseapp.com',
    storageBucket: 'evently-events.firebasestorage.app',
    measurementId: 'G-M5K7H0J7E7',
  );

}