// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WebKey']??'',
    appId: '1:32266065148:web:f8c5d94faef0d7397cf379',
    messagingSenderId: '32266065148',
    projectId: 'evently-events',
    authDomain: 'evently-events.firebaseapp.com',
    storageBucket: 'evently-events.firebasestorage.app',
    measurementId: 'G-M0K04G6NKN',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey:dotenv.env ['AndroidKey']??'',
    appId: '1:32266065148:android:78a00bde847624977cf379',
    messagingSenderId: '32266065148',
    projectId: 'evently-events',
    storageBucket: 'evently-events.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey:dotenv.env ['IOSKey']??"",
    appId: '1:32266065148:ios:95b52242f326677a7cf379',
    messagingSenderId: '32266065148',
    projectId: 'evently-events',
    storageBucket: 'evently-events.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['MacOSKey']??'',
    appId: '1:32266065148:ios:95b52242f326677a7cf379',
    messagingSenderId: '32266065148',
    projectId: 'evently-events',
    storageBucket: 'evently-events.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['WindowsKey']??'',
    appId: '1:32266065148:web:8f0f4b44c71a5dbc7cf379',
    messagingSenderId: '32266065148',
    projectId: 'evently-events',
    authDomain: 'evently-events.firebaseapp.com',
    storageBucket: 'evently-events.firebasestorage.app',
    measurementId: 'G-M5K7H0J7E7',
  );

}